/**
 * Copyright (c) 2018 Ken Erney
 *
 * This file is part of the aismsg_pi distribution, and OpenCPN Plugin.
 *
 * aismsg_pi is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * aismsg_pi is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with aismsg_pi.  If not, see <https://www.gnu.org/licenses/>.
 */

#ifndef __AISMSGPREFSSDIALOG_H__
#define __AISMSGPREFSSDIALOG_H__

/**
@file Subclass of AISMsgSettingsDialogBase, which is generated by wxFormBuilder.
*/

#include "AISMsgUIBase.h"

#define AISMSG_MMSI_LEN		9 // length used to validate MMSI

class AISMsgPrefsDialog : public AISMsgPrefsDialogBase
{
	protected:
		void OnEnableBBM( wxCommandEvent& event );
		void OnEnableABM( wxCommandEvent& event );
		void OnOk( wxCommandEvent& event );

	public:
		AISMsgPrefsDialog( wxWindow* parent );
};

#endif // __AISMSGPREFSSDIALOG_H__
