/* Autogenerated by png2wx.pl on Wed Jul 18 22:16:51 2018 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_aismsg;
extern wxBitmap *_img_aismsg_pi;

#endif /* ICONS_H */
